# Generated by Django 4.2.4 on 2023-09-26 16:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NidhiEIR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('dateOfBirth', models.DateField()),
                ('address', models.TextField()),
                ('education', models.TextField()),
                ('experience', models.TextField()),
                ('ideaDescription', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer Not to Say', 'Prefer Not to Say')], default='None', max_length=20)),
                ('category', models.CharField(choices=[('General', 'General'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST')], default='None', max_length=10)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('conceptNote', models.FileField(upload_to='notes/')),
                ('aspectNote', models.FileField(upload_to='notes/')),
                ('previousRecipient', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('fullCommitment', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('noOtherFellowship', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('businessCommitment', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('notBeneficiary', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('registerPEP', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
            ],
        ),
    ]
