# Generated by Django 4.2.4 on 2023-08-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_events_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['eventDate'], 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
