# Generated by Django 4.2.1 on 2023-09-01 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_events_options_alter_events_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='occured',
        ),
    ]
