# Generated by Django 4.2.1 on 2023-09-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_contactus_email_alter_contactus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(upload_to='event_images/'),
        ),
    ]
